Live site version 4.1.1 update (#539)
* try fixing unsafe code (#484)

* try fixing unsafe code

* use a byte array

* Gaia Shortcut (#477)

* Town Tile enums; new flag: Gaia Shortcut, with child: Move Gaia Item Shop

* cleanup

* create tooltips

* Bump to 4.1.0

* Extensive Hint Flag (#469)

* Initial Commit

* Done some Change Requests

* Quest Items are always treated as incentivized, that way there will be hints, even if you don't use the incentive functionality.
The system is now only using TextIds used exclusively by the randomly selected NPCs. This might restrict the amount of hints that can be placed.

* some corrections

* remove duplicate hints, not perfect, but ok i guess...

* Changed up teh configuration of the hint system, to make it easier to understand.
Needed to change the processing as well, to acomodate the new system.

* Default Flags changed
Hinted npcs set to stationary
Hint are more deatiled
Sage in coneria states the total count of actual loose

* let's not be too stupid

* Reworked the class structure to be easier to extend

* Fixed Sparkle hint to 1000G per floor

Co-authored-by: Martin Hammerl <martin.hammerl@kwb.at>

* Shop Reduction (#470)

* Initial Commit

* Removed StartingInventory

* removed whitespace

* removed unused enum

* removed unnessecary(uhh, i can't write today) debug code

* self-containing

Co-authored-by: Martin Hammerl <martin.hammerl@kwb.at>

* Legendary Shops (#475)

* Legendary Shops

* Added Flags to Experimental Tab

Co-authored-by: Martin Hammerl <martin.hammerl@kwb.at>

* Nones Gain XP (#479)

* NonesGainXP flag

* NonesGainXP asm file

* Ethers (#480)

* Turn shelters into ethers

* Turn shelters into ethers

* Added .asm file to ff1lib

* Added comment referencing asm file

* Neutering MemTable usage (#486)

* Revert "Neutering MemTable usage (#486)" (#487)

Fixing Memtable to work without unsafe code

This reverts commit 8174742ff57cdd9856a15901da9af7b4731fa1f7.

Co-authored-by: mhn65536 <x.y@z.uk>

* Highlight selected preset

* Fix windows line endings for .cs, .cshtml, .xaml, and .razor (#488)

* Refill Experimnental tab (#489)

* Make LegendaryShops spellcrafterproof (#490)

Co-authored-by: x <y@z.a>

* Small layout fixes

* Beginner preset

* Fix checkbox label

* Add Coneria to Town Shuffle! (#481)

* Add Coneria to Town Shuffle!

With requisite accommodations.

* Only lock the entrance to a town if Allow Unsafe Start Area is
unchecked.

* Better checkbox label fix

* tooltip updates for 4.1.x (#491)

* json update for all tooltips

* images for tooltip updates

* Fix tooltips

* New favicon

* Enum fix and more checkbox fix

* tooltip img correction for ShopReduction (#495)

* fix tooltip image; was: gaiaShortcut now: shopReduction

* fix typo

* Experimental Tab Layout fix

* Announcement Box

* Improve tooltip.

* Fix empty party bug

* Rewrite the README to be developer focused (#496)

* wip - readme rewrite

* run a spell checker

* wip - how to create a branch and merge stuff

* add info about the deployment process

* A few typo and proposed randomizer definition

* spelling

Co-authored-by: wildham0 <64616385+wildham0@users.noreply.github.com>
Co-authored-by: Mike Lattanzio <latzio@gmail.com>

* Deep Dungeon (#482)

* Added flag for Deep Dungeon

* Coneria jail implemented and castle teleport adjusted

* Rudimentary procedural generation working, first floor only

* Generates rooms and connects floors with staircases

* Generates rooms and connects floors with staircases

* Entire dungeon is connected, monster domains sorted by power level

* Town branches working, fixed bug with room placement

* Treasures are populating but there's something wrong

* Everything should be working now, just a few more tests

* Fixed a few bugs relating to chest placement

* Fixed bugs, Gaia and Onrac swapped, submarine removed

* Added tooltip, cleaned up code/comments a bit

* Added tooltip image

* Actually commit those conflict resolutions

* Credits updates.

* Deep dungeon help.

* Orbs Easter Egg (#498)

* make that orbs easter egg real

* easy to read orbs debugging

* comment out the orbs easter egg pattern output

* set the z-index reasonably

* Move orb backs to NavMenu

Co-authored-by: wildham0 <64616385+wildham0@users.noreply.github.com>

* Fix SpookyFlag full inventory bug

* fix the readme by adding a single space (#502)

* Content (#504)

* content updates (re-do)

updates what's new and about, adds in full resources section

* images for new content

* Add files via upload

* Add files via upload

* Add files via upload

* Add Resources button + small fixes

* Image Viewer (#507)

* Add image viewer

* Bump version to 4.1.1

* Update change log

* Magic Shop Locations: Paired Shuffle (#492)

* Magic Shop Location Pairs

* tooltips; gif courtesy of darkmoonfirelyte

* cleanup

* Alternate Fiends (#509)

* Initial commit

* Insertion routines

* AltFiends struct

* Complete Function

* Make flags

* Fix Trapped Chests safety bug (#510)

* Fix AlternateFiends skill bug

* change the checkbox for final fight formations to a dropdown and also run the builtin formatter with our .editorconfig settings in a couple files I touche. (#511)

* Add ToFR Exit (#494)

* Add ToFR Exit

* shortToFR func checks ToFRExit flag, not ToFRExit func checks shortToFR flag

* Lifereboot/20210219 tool tip markup (#513)

* fix typo

* create simple [grid] markup for tooltips

* community preferred cell data centered

* Random Incentive Location Selection (#512)

* Added Elemental/Type damage bonus.

* Added a slider to give the flag creator the control over elemental/type weapon weakness.

* Added a flag to remove masamune.

* Added selection to randomized incentives by location.

* Changed Selection to drop down to let the user pick between full random at location, behind or before gating at locations.

* Loose Exclude Incentivized Dungeons (#516)

* Puts a clinic in Melmond (#505)

* Added flag to give Melmond a clinic

* Disabled flag when recruitment mode on

* Revert "Disabled flag when recruitment mode on"

This reverts commit c5257ce3f228c21cf118ec1db1b291e105046402.

* Make Tavern Mode work with the Melmond clinic

Co-authored-by: Steven Biro <steven.biro@mail.utoronto.ca>
Co-authored-by: Steven <Steven-Biro@users.noreply.github.com>

* Causes the vampire to attack a random town instead of always Melmond (#517)

* Causes the vampire to attack a random town instead of always Melmond

* Tri-stated the flag and gave Melmond the item shop of the destroyed town

* Disable LichsRevenge if Enemizer is enabled

* Fix for long tooltips on mobile

* Fix size unit

* BlursedClass fix conflicting blessings

* Consumable Treasure Stack Size (#520)

* Consumable Treasure Stack Size

* added asms, disassembled from blobs and checked for correctness

* corrected blob and location of dropdownlist

* corrected some bugs

* tooltip

Co-authored-by: Martin Hammerl <martin.hammerl@kwb.at>
Co-authored-by: x.y <x.y@z.a>

* Lifereboot/20210222 titan snack (#519)

* fix typo

* titan snack fun flag

* cleanup

* tooltip

* titan snack fun flag

* cleanup

* tooltip

* per wildham, reset rng every fun flag

* update list contents per community suggestions

* remove duplicate

* ClassAsNpc, put Sarda's npc in more convenient location

* (UI) Fix Blursed Gear visual bug (#526)

* Fix visual bug with blurse slider

* Fix error

* Lifereboot/20210301 lute plate in short tofr (#524)

* include lute plate in short ToFR

* decouple Free Lute and Shorten ToFR

* lute plate single color via transparent garland

* tooltip

* Moved MP subroutine so it no longer conflicts with Floater code (#521)

* Fix typecasting error (#527)

"error CS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)"

* More Consumalbe Chests (#523)

* More Consumable Chests

* minor changes

* reverted to guts feeling

* Update tooltips.json

* You wanted it...

* Refactor reading ClassData from RandomizeClass to be usable elsewhere (#529)

Switches a few functions in BugFixes.cs over to using ReadClassData()
and WriteClassData().

* ChanceToRun (#528)

* Deepdungeon Warp Zone (#522)

* Compatible with Enemizer. No longer generates shelters unless Etherizer is on.

* Added flag for distributing deep dungeon treasure evenly instead of progressively

* Added warp zone

* Lifereboot/20210303 fight bahamut (#525)

* fight bahamut flag

* cleanup

* tooltip

* handle Shuffle Astos; disable when SpookyFlag

* disable when Enemizer

* Better + sign

* remove Bahamut encounter properly (#535)

* Fix npc hint typo

* Adds a dock to Bahamut's island so that airship is not required for class change. (#532)

* Adds a dock to Bahamut's island so that airship is not required for class change.

* Adjust map location requirements when Bahamut dock is enabled.

* Add bahamut dock screenshot for tooltip

* Fix missing tooltip for Bahamut Cardia dock flag. (#536)

* StartingLevels (#530)

* StartingLevels

* asm doc

* moved bit to game_flags

* Increase thief starting agility, agility growth, and starting evade. (#531)

This is to make it more viable as a first-slot character and
compensate for its poor HP, absorb and mdef compared to the fighter
and black belt.

A starting AGI of 120 was selected after a lot of spread sheet number
crunching and a few test seeds at various agility values.

This gives the thief a starting evade (E) of 168.  Because the base
to-hit value is also 168, and the to-hit calculation is (168-E+H),
this means the monster's accuracy value (H) dominates in determining
if how easily the thief can be hit.  Vanilla monster accuracy ranges
from 2 (imps) to 114 (Kraken 2) to 200
(Chaos), with the majority of monsters having
accuracy in the 20-80 range.

This means a monster with an accuracy of 50 should have about a 25%
chance of hitting the thief.

HOWEVER monster accuracy gets scaled along with all the other monster
stats, so in practice most of the more dangerous monsters don't have
much trouble landing blows.

Another implication for combat is that enemies that have multiple
attacks (most notabliy Kary and Kraken) will tend to miss _some_ hits,
but not all.  This compensates for the fact that the ninja has garbage
HP growth.  A knight with 600 HP can tank 400 HP of damage and
survive, a ninja with 400 HP can evade half the blows and take 200 HP
of damage, with the same outcome.

The agility stat, together with the luck stat, plays a role in
determining whether the party is "suprised" or gets "first strike".
This is called "initiative".  The calculation also incorporates a
"suprise factor" of the monster formation.  For most formations, the
suprise factor is 4.  A first-slot thief will have about a 25% chance
of getting first strike.  This sounds like a lot, except a) some
formations have higher suprise factors.  b) you can't first strike
unrunnable formations
(unless you enable the
UnrunnablesStrikeFirstAndSurprise flag)

For formations with a higher surprise factor, the thief has a
smaller (or even zero) chance to get first strike -- but the thief's
initiative also makes also less likely (or zero) that the party will
be surprised.  This turns out to be a subtle but important
contribution to surviability, by reducing the incidence of
party-wiping ambushes.

Overall, having playing a test seed with a lead thief, it didn't feel
overpowered.

a) This only reduces damage taken from basic melee.  The thief remains
as vulnerable as ever to spells, sleep/stun, and still has lousy HP
growth and (prior to class change) weapon and armor selection compared
to the knight.

b) The buff to the suprise/first stike calculation is mainly useful
for avoiding combat, not overcoming difficult battles.

That said, it's possible this could be somewhat more unbalancing with
3 warrior or 2 warrior teams -- we can always dial this back or add
options based on community feedback.

* Rand vamp atk improvements (#537)

random vamp attack changes:

.Lefeinish Hospitality compatible (Inn available, Clinic unavailable)
.Include Coneria subflag
.tooltips

* (bugfix) BlursedClass +2mdef bonus fix

Co-authored-by: HQS <highqualityshaun@gmail.com>
Co-authored-by: wildham0 <64616385+wildham0@users.noreply.github.com>
Co-authored-by: mhn65536 <53567009+mhn65536@users.noreply.github.com>
Co-authored-by: Martin Hammerl <martin.hammerl@kwb.at>
Co-authored-by: pinkpuff <kalel.of.krypton@gmail.com>
Co-authored-by: mhn65536 <x.y@z.uk>
Co-authored-by: Mike Lattanzio <latzio@gmail.com>
Co-authored-by: x <y@z.a>
Co-authored-by: darkmoonfirelyte <51683874+darkmoonfirelyte@users.noreply.github.com>
Co-authored-by: iwritecode791 <59264739+iwritecode791@users.noreply.github.com>
Co-authored-by: x.y <x.y@z.a>
Co-authored-by: Peter Amstutz <tetron@interreality.org>
Co-authored-by: Peter Amstutz <peter.amstutz@curii.com>